fixing: Erro da API ao fazer POST | Erro conversão GeoJSON
Exception: "Unable to convert to python object: String input unrecognized as WKT EWKT, and HEXEWKB."