fixing: Erro da API ao fazer POST | Falha em String -> GeoJSON
Exception: "Unable to convert to python object: String input unrecognized as WKT EWKT, and HEXEWKB."

Localização está sendo passada como String, com a API esperando no formato GeoJSON.

Tentativa: Implementar try-catch e fazer a conversão dos valores da localização.